### PR TITLE
updated SDKs

### PR DESCRIPTION
**Pull request by jpriebe**
Updated to Ti mobile SDK 4.1.0

Updated to the latest Flurry SDKs (5.6.0 for android, 6.7.0 for ios)

### CODE REVIEW

**Comment by jpriebe** [comment]
I signed the CLA (the Adobe / Github integration didn't work in Chrome, so I had to switch over to Firefox to get that to go through).  Hopefully, the "Appcelerator-CLA check" that is failing will eventually clear.

**Comment by jpriebe** [comment]
Looks like my CLA did go through, but now the CI build is failing.

I don't think the errors in the CI build are anything I can control; they look more like issues with the path to various tools in the build environment.

**Comment by jpriebe** [comment]
Any update on this?

**Comment by hansemannn** [comment]
Hey @jpriebe, sorry for the long delay. I would like to use your PR instead of mine [here](https://github.com/appcelerator-archive/ti.flurry/pull/34). Can you resolve the merge conflicts?

**Comment by jpriebe** [comment]
@hansemannn - rebased, and conflicts resolved.  Note: my version numbering strategy is a little different from yours; I updated the minor version number each time I upgraded the flurry libraries, whereas I think you were just updating the patch number.  I hope that's OK with you.

**Comment by jpriebe** [comment]
@hansemannn - I just merged again to remove the conflicts.  Do you want this PR?

**Comment by hansemannn** [comment]
Sorry @jpriebe, I missed the updates! In the meantime, some of the changes are already done by other commits I think, but if you can rebase one last time, I'll get you a proper review :-)

**Comment by jpriebe** [comment]
rebased.  I didn't change your version number, so you might want to have a look at the manifests.

**Pull request merged**
